spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/myapp
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.practiceBack.dto
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
